//! IR → valibot TypeScript source.
//!
//! The output is not a bespoke validator: it is ordinary valibot code
//! (`import * as v from 'valibot'`) plus `v.InferOutput` type exports — the
//! exact library the frontend already uses.

use crate::ir::*;
use std::collections::BTreeSet;

const HEADER: &str =
    "// @generated by apps/bff-rs `contract-codegen` — do not edit by hand.\n// Source of truth: apps/bff-rs/crates/contract/src/schemas/. Run `bun run codegen:contracts`.\n";

/// Emit every module to `(filename, contents)` pairs, plus an `index.gen.ts`
/// barrel. The `.gen.ts` suffix keeps Biome (which ignores `**/*.gen.ts`) from
/// reformatting generated output and fighting the `--check` drift guard.
pub fn emit_all(reg: &Registry) -> Vec<(String, String)> {
    let mut files: Vec<(String, String)> = reg
        .modules
        .iter()
        .map(|m| (format!("{}.gen.ts", m.name), emit_module(reg, m)))
        .collect();
    files.push(("index.gen.ts".to_string(), emit_barrel(reg)));
    files
}

fn emit_module(reg: &Registry, module: &Module) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');

    out.push_str("import * as v from 'valibot';\n");

    // Cross-module imports: names this module references that live elsewhere.
    let mut by_module: std::collections::BTreeMap<&'static str, BTreeSet<&'static str>> =
        std::collections::BTreeMap::new();
    for name in referenced_names(module) {
        if let Some(owner) = reg.module_of(name) {
            if owner != module.name {
                by_module.entry(owner).or_default().insert(name);
            }
        }
    }
    for (owner, names) in &by_module {
        let list = names.iter().copied().collect::<Vec<_>>().join(", ");
        out.push_str(&format!("import {{ {list} }} from './{owner}.gen';\n"));
    }
    out.push('\n');

    // Declarations (consts + schemas) in source order.
    for decl in &module.decls {
        emit_decl(reg, decl, &mut out);
    }

    // Type exports, grouped at the bottom (matches the hand-written style).
    let type_exports: Vec<String> = module
        .decls
        .iter()
        .filter_map(|d| match d {
            Decl::Schema {
                name, ty: Some(ty), ..
            } => Some(format!(
                "export type {ty} = v.InferOutput<typeof {name}>;\n"
            )),
            _ => None,
        })
        .collect();
    if !type_exports.is_empty() {
        out.push('\n');
        for line in type_exports {
            out.push_str(&line);
        }
    }

    out
}

fn emit_decl(reg: &Registry, decl: &Decl, out: &mut String) {
    match decl {
        Decl::ConstStrArray { name, doc, values } => {
            emit_doc(doc, out);
            let items = values
                .iter()
                .map(|v| format!("'{v}'"))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("export const {name} = [{items}] as const;\n"));
        }
        Decl::ConstNum { name, doc, value } => {
            emit_doc(doc, out);
            out.push_str(&format!("export const {name} = {};\n", fmt_num(*value)));
        }
        Decl::ConstStr { name, doc, value } => {
            emit_doc(doc, out);
            out.push_str(&format!("export const {name} = '{value}';\n"));
        }
        Decl::Schema {
            name,
            doc,
            exported,
            schema,
            ..
        } => {
            emit_doc(doc, out);
            let kw = if *exported { "export const" } else { "const" };
            out.push_str(&format!("{kw} {name} = {};\n", emit_schema(reg, schema)));
        }
    }
}

fn emit_doc(doc: &Option<&'static str>, out: &mut String) {
    if let Some(text) = doc {
        if text.contains('\n') {
            out.push_str("/**\n");
            for line in text.lines() {
                out.push_str(&format!(" * {line}\n"));
            }
            out.push_str(" */\n");
        } else {
            out.push_str(&format!("/** {text} */\n"));
        }
    }
}

/// Emit a single schema as a valibot expression.
pub fn emit_schema(reg: &Registry, schema: &Schema) -> String {
    match schema {
        Schema::String(actions) => {
            if actions.is_empty() {
                "v.string()".to_string()
            } else {
                let mut parts = vec!["v.string()".to_string()];
                parts.extend(actions.iter().map(emit_str_action));
                format!("v.pipe({})", parts.join(", "))
            }
        }
        Schema::Number(actions) => {
            if actions.is_empty() {
                "v.number()".to_string()
            } else {
                let mut parts = vec!["v.number()".to_string()];
                parts.extend(actions.iter().map(emit_num_action));
                format!("v.pipe({})", parts.join(", "))
            }
        }
        Schema::Boolean => "v.boolean()".to_string(),
        Schema::PicklistConst(name) => format!("v.picklist({name})"),
        Schema::Ref(name) => name.to_string(),
        Schema::Array(inner) => format!("v.array({})", emit_schema(reg, inner)),
        Schema::Nullable(inner) => format!("v.nullable({})", emit_schema(reg, inner)),
        Schema::Optional(inner, default) => match default {
            None => format!("v.optional({})", emit_schema(reg, inner)),
            Some(Default::Null) => format!("v.optional({}, null)", emit_schema(reg, inner)),
        },
        Schema::Object(obj) => emit_object(reg, obj),
        Schema::Checked(inner, check) => format!(
            "v.pipe(\n  {},\n  v.check(({}) => {}, '{}'),\n)",
            indent(&emit_schema(reg, inner)),
            check.param,
            check.body,
            check.message,
        ),
    }
}

/// Indent the *continuation* lines of a nested expression by one level, so a
/// child object/pipe lines up under the parent that embeds it. The first line
/// is left alone — the caller has already placed it after `name: `.
fn indent(source: &str) -> String {
    source.replace('\n', "\n  ")
}

fn emit_object(reg: &Registry, obj: &ObjectSchema) -> String {
    if obj.items.is_empty() {
        return "v.object({})".to_string();
    }
    let mut lines = String::new();
    for item in &obj.items {
        match item {
            ObjectItem::Field { name, doc, schema } => {
                if let Some(text) = doc {
                    if text.contains('\n') {
                        lines.push_str("  /**\n");
                        for l in text.lines() {
                            lines.push_str(&format!("   * {l}\n"));
                        }
                        lines.push_str("   */\n");
                    } else {
                        lines.push_str(&format!("  /** {text} */\n"));
                    }
                }
                lines.push_str(&format!(
                    "  {name}: {},\n",
                    indent(&emit_schema(reg, schema))
                ));
            }
            ObjectItem::Spread(ref_name) => {
                lines.push_str(&format!("  ...{ref_name}.entries,\n"));
            }
        }
    }
    format!("v.object({{\n{lines}}})")
}

fn emit_str_action(action: &StringAction) -> String {
    match action {
        StringAction::Trim => "v.trim()".to_string(),
        StringAction::MinLength(n) => format!("v.minLength({})", emit_num_arg(n)),
        StringAction::MaxLength(n) => format!("v.maxLength({})", emit_num_arg(n)),
        StringAction::NonEmpty => "v.nonEmpty()".to_string(),
        StringAction::Email => "v.email()".to_string(),
        StringAction::IsoDate => "v.isoDate()".to_string(),
        StringAction::IsoTime => "v.isoTime()".to_string(),
    }
}

fn emit_num_action(action: &NumberAction) -> String {
    match action {
        NumberAction::Integer => "v.integer()".to_string(),
        NumberAction::MinValue(n) => format!("v.minValue({})", emit_num_arg(n)),
        NumberAction::MaxValue(n) => format!("v.maxValue({})", emit_num_arg(n)),
    }
}

fn emit_num_arg(arg: &NumArg) -> String {
    match arg {
        NumArg::Lit(n) => fmt_num(*n),
        NumArg::Const(name) => name.to_string(),
    }
}

fn fmt_num(n: f64) -> String {
    if n.fract() == 0.0 {
        format!("{}", n as i64)
    } else {
        format!("{n}")
    }
}

/// Names a module references (schema refs, picklist consts, minLength/minValue
/// const args) — used to compute cross-module imports.
fn referenced_names(module: &Module) -> BTreeSet<&'static str> {
    let mut set = BTreeSet::new();
    for decl in &module.decls {
        if let Decl::Schema { schema, .. } = decl {
            collect_refs(schema, &mut set);
        }
    }
    set
}

fn collect_refs(schema: &Schema, set: &mut BTreeSet<&'static str>) {
    match schema {
        Schema::Ref(name) | Schema::PicklistConst(name) => {
            set.insert(name);
        }
        Schema::String(actions) => {
            for a in actions {
                match a {
                    StringAction::MinLength(NumArg::Const(c))
                    | StringAction::MaxLength(NumArg::Const(c)) => {
                        set.insert(c);
                    }
                    _ => {}
                }
            }
        }
        Schema::Number(actions) => {
            for a in actions {
                match a {
                    NumberAction::MinValue(NumArg::Const(c))
                    | NumberAction::MaxValue(NumArg::Const(c)) => {
                        set.insert(c);
                    }
                    _ => {}
                }
            }
        }
        Schema::Array(inner) | Schema::Nullable(inner) | Schema::Optional(inner, _) => {
            collect_refs(inner, set)
        }
        Schema::Checked(inner, _) => collect_refs(inner, set),
        Schema::Object(obj) => {
            for item in &obj.items {
                match item {
                    ObjectItem::Field { schema, .. } => collect_refs(schema, set),
                    ObjectItem::Spread(name) => {
                        set.insert(name);
                    }
                }
            }
        }
        Schema::Boolean => {}
    }
}

fn emit_barrel(reg: &Registry) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    for m in &reg.modules {
        out.push_str(&format!("export * from './{}.gen';\n", m.name));
    }
    out
}
