/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignupRouteRouteImport } from './routes/_public/signup/route'
import { Route as PublicLoginRouteRouteImport } from './routes/_public/login/route'
import { Route as AppTodayRouteRouteImport } from './routes/_app/today/route'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppTasksNewRouteRouteImport } from './routes/_app/tasks/new/route'
import { Route as AppTasksTaskIdRouteRouteImport } from './routes/_app/tasks/$taskId/route'
import { Route as AppProjectsProjectIdRouteRouteImport } from './routes/_app/projects/$projectId/route'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignupRouteRoute = PublicSignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRouteRoute = PublicLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppTodayRouteRoute = AppTodayRouteRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksNewRouteRoute = AppTasksNewRouteRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksTaskIdRouteRoute = AppTasksTaskIdRouteRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsProjectIdRouteRoute =
  AppProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/today': typeof AppTodayRouteRoute
  '/login': typeof PublicLoginRouteRoute
  '/signup': typeof PublicSignupRouteRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRouteRoute
  '/tasks/new': typeof AppTasksNewRouteRoute
  '/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/today': typeof AppTodayRouteRoute
  '/login': typeof PublicLoginRouteRoute
  '/signup': typeof PublicSignupRouteRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRouteRoute
  '/tasks/new': typeof AppTasksNewRouteRoute
  '/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_app/today': typeof AppTodayRouteRoute
  '/_public/login': typeof PublicLoginRouteRoute
  '/_public/signup': typeof PublicSignupRouteRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRouteRoute
  '/_app/tasks/new': typeof AppTasksNewRouteRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/today'
    | '/login'
    | '/signup'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/today'
    | '/login'
    | '/signup'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_public'
    | '/_app/today'
    | '/_public/login'
    | '/_public/signup'
    | '/_app/projects/$projectId'
    | '/_app/tasks/$taskId'
    | '/_app/tasks/new'
    | '/_app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tasks/new': {
      id: '/_app/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AppTasksNewRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppTodayRouteRoute: typeof AppTodayRouteRoute
  AppProjectsProjectIdRouteRoute: typeof AppProjectsProjectIdRouteRoute
  AppTasksTaskIdRouteRoute: typeof AppTasksTaskIdRouteRoute
  AppTasksNewRouteRoute: typeof AppTasksNewRouteRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppTodayRouteRoute: AppTodayRouteRoute,
  AppProjectsProjectIdRouteRoute: AppProjectsProjectIdRouteRoute,
  AppTasksTaskIdRouteRoute: AppTasksTaskIdRouteRoute,
  AppTasksNewRouteRoute: AppTasksNewRouteRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRouteRoute: typeof PublicLoginRouteRoute
  PublicSignupRouteRoute: typeof PublicSignupRouteRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRouteRoute: PublicLoginRouteRoute,
  PublicSignupRouteRoute: PublicSignupRouteRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
